version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server/data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  
    volumes:
      - ./client:/app  
      - /app/node_modules  
    environment:
      - CHOKIDAR_USEPOLLING=true  
    depends_on:
      - backend
    restart: unless-stopped